services:
  openWebUI:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    # Ports config isn't required beacuse of "network_mode: host"
    # Access OpenWebUI on 8080
    # ports: 
    #   - "3000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data
    network_mode: host 
 
  ollama:
    build: ./ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-local:/root/.ollama

volumes:
  ollama-local:
    external: true
  open-webui-local:
    external: true
